# Generated by Django 3.2.4 on 2021-09-04 10:57

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('volatility', models.IntegerField(blank=True, default=0)),
                ('type', models.CharField(blank=True, max_length=40)),
                ('price', models.FloatField(blank=True, default=0.0)),
                ('var', models.IntegerField(blank=True, default=0)),
                ('tog', models.IntegerField(blank=True, default=0)),
                ('pne', models.FloatField(blank=True, default=0.0)),
                ('debt_load', models.FloatField(blank=True, default=0.0)),
                ('capm', models.FloatField(blank=True, default=0.0)),
                ('spoint', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('cost', models.FloatField(blank=True, default=0.0)),
                ('risk_status', models.CharField(blank=True, default='medium', max_length=20)),
                ('limit', models.IntegerField(blank=True, default=0)),
                ('predicted_income', models.IntegerField(blank=True, default=0)),
                ('risk', models.IntegerField(blank=True, default=0)),
                ('year_income', models.IntegerField(blank=True, default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('recommended_securities', models.ManyToManyField(blank=True, related_name='portfolio_recommended_securities', to='main.Security')),
                ('securities', models.ManyToManyField(blank=True, related_name='portfolio_securities', to='main.Security')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='ExtendedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='User Email')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
