# Generated by Django 3.2.4 on 2021-09-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='capm',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
