# Generated by Django 3.2.4 on 2021-09-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='year_change',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
