# Generated by Django 3.2.4 on 2021-09-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_portfolio_capm'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='volatility',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
